name: Build
on: [push, pull_request, release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          submodules: true

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v8
        with:
          name: decorated-cospans
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: ./scripts/pushCachix
